# Generated by Django 3.0.4 on 2020-06-02 06:03

from django.db import migrations, models
import work.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConstantEg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Raw_coal', models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='原煤')),
                ('Clean_coal', models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='洗精煤')),
                ('Coke', models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='焦炭')),
                ('Briquette', models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='型煤')),
                ('Other_coking_products', models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='其他焦化产品')),
                ('Crude', models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='原油')),
                ('Fuel_oil', models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='燃料油')),
                ('Gasoline', models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='汽油')),
                ('Diesel', models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='柴油')),
                ('Kerosene', models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='煤油')),
                ('Liquefied_petroleum_gas', models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='液化石油气')),
                ('Refinery_dry_gas', models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='炼厂干气')),
                ('Naphtha', models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='石脑油')),
                ('Asphalt', models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='沥青')),
                ('Lubricating_oil', models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='润滑油')),
                ('Petroleum_coke', models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='石油焦')),
                ('Natural_gas', models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='天然气')),
                ('Cement', models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='水泥')),
                ('Steel', models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='钢铁')),
                ('Farmland', models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='农地')),
                ('Woodland', models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='林地')),
                ('Pastureland', models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='畜牧地')),
                ('Fishing_ground', models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='渔场')),
                ('Construction_land', models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='建设用地')),
                ('Raw_coal_MJ', models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='原煤热值')),
                ('Clean_coal_MJ', models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='洗精煤热值')),
                ('Coke_MJ', models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='焦炭热值')),
                ('Briquette_MJ', models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='型煤热值')),
                ('Other_coking_products_MJ', models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='其他焦化产品热值')),
                ('Crude_MJ', models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='原油热值')),
                ('Fuel_oil_MJ', models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='燃料油热值')),
                ('Gasoline_MJ', models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='汽油热值')),
                ('Diesel_MJ', models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='柴油热值')),
                ('Kerosene_MJ', models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='煤油热值')),
                ('Liquefied_petroleum_gas_MJ', models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='液化石油气热值')),
                ('Refinery_dry_gas_MJ', models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='炼厂干气热值')),
                ('Naphtha_MJ', models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='石脑油热值')),
                ('Asphalt_MJ', models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='沥青热值')),
                ('Lubricating_oil_MJ', models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='润滑油热值')),
                ('Petroleum_coke_MJ', models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='石油焦热值')),
                ('Natural_gas_MJ', models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='天然气热值')),
            ],
            options={
                'verbose_name': '能源常量',
            },
        ),
    ]
