# Generated by Django 3.0.4 on 2020-06-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basework', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calculated_value',
            old_name='CO2_Emission',
            new_name='CO2_Emission_a',
        ),
        migrations.RenameField(
            model_name='calculated_value',
            old_name='GHG_Emission',
            new_name='GHG_Emission_a',
        ),
        migrations.RenameField(
            model_name='prov_calculated_value',
            old_name='CO2_Emission',
            new_name='CO2_Emission_a',
        ),
        migrations.RenameField(
            model_name='prov_calculated_value',
            old_name='GHG_Emission',
            new_name='GHG_Emission_a',
        ),
        migrations.AddField(
            model_name='calculated_value',
            name='CO2_Emission_b',
            field=models.FloatField(blank=True, null=True, verbose_name='二氧化碳排放量_年度计算值'),
        ),
        migrations.AddField(
            model_name='calculated_value',
            name='GHG_Emission_b',
            field=models.FloatField(blank=True, null=True, verbose_name='温室气体排放量_年度计算值'),
        ),
        migrations.AddField(
            model_name='prov_calculated_value',
            name='CO2_Emission_b',
            field=models.FloatField(blank=True, null=True, verbose_name='二氧化碳排放量_年度计算值'),
        ),
        migrations.AddField(
            model_name='prov_calculated_value',
            name='GHG_Emission_b',
            field=models.FloatField(blank=True, null=True, verbose_name='温室气体排放量_年度计算值'),
        ),
    ]
