# Generated by Django 3.0.4 on 2020-06-10 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basework', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportFile_excel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excelfile', models.FileField(upload_to='data/', verbose_name='上传')),
                ('name', models.CharField(max_length=50, verbose_name='文件名')),
            ],
            options={
                'verbose_name': '数据导入',
            },
        ),
    ]
