# Generated by Django 3.0.4 on 2020-06-10 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basework', '0002_importfile_excel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annual_data',
            name='Consume_Asphalt',
            field=models.FloatField(blank=True, verbose_name='沥青消耗量'),
        ),
        migrations.AlterField(
            model_name='annual_data',
            name='Consume_Briquette',
            field=models.FloatField(blank=True, verbose_name='型煤消耗量'),
        ),
        migrations.AlterField(
            model_name='annual_data',
            name='Consume_Cement',
            field=models.FloatField(blank=True, verbose_name='水泥消耗量'),
        ),
        migrations.AlterField(
            model_name='annual_data',
            name='Consume_Clean_coal',
            field=models.FloatField(blank=True, verbose_name='洗精煤消耗量'),
        ),
        migrations.AlterField(
            model_name='annual_data',
            name='Consume_Coke',
            field=models.FloatField(blank=True, verbose_name='焦炭消耗量'),
        ),
        migrations.AlterField(
            model_name='annual_data',
            name='Consume_Construction_land',
            field=models.FloatField(blank=True, verbose_name='建设用地消耗量'),
        ),
        migrations.AlterField(
            model_name='annual_data',
            name='Consume_Crude',
            field=models.FloatField(blank=True, verbose_name='原油消耗量'),
        ),
        migrations.AlterField(
            model_name='annual_data',
            name='Consume_Diesel',
            field=models.FloatField(blank=True, verbose_name='柴油消耗量'),
        ),
        migrations.AlterField(
            model_name='annual_data',
            name='Consume_Farmland',
            field=models.FloatField(blank=True, verbose_name='农地消耗量'),
        ),
        migrations.AlterField(
            model_name='annual_data',
            name='Consume_Fishing_ground',
            field=models.FloatField(blank=True, verbose_name='渔场消耗量'),
        ),
        migrations.AlterField(
            model_name='annual_data',
            name='Consume_Fuel_oil',
            field=models.FloatField(blank=True, verbose_name='燃料油消耗量'),
        ),
        migrations.AlterField(
            model_name='annual_data',
            name='Consume_Gasoline',
            field=models.FloatField(blank=True, verbose_name='汽油消耗量'),
        ),
        migrations.AlterField(
            model_name='annual_data',
            name='Consume_Kerosene',
            field=models.FloatField(blank=True, verbose_name='煤油消耗量'),
        ),
        migrations.AlterField(
            model_name='annual_data',
            name='Consume_Liquefied_petroleum_gas',
            field=models.FloatField(blank=True, verbose_name='液化石油气消耗量'),
        ),
        migrations.AlterField(
            model_name='annual_data',
            name='Consume_Lubricating_oil',
            field=models.FloatField(blank=True, verbose_name='润滑油消耗量'),
        ),
        migrations.AlterField(
            model_name='annual_data',
            name='Consume_Naphtha',
            field=models.FloatField(blank=True, verbose_name='石脑油消耗量'),
        ),
        migrations.AlterField(
            model_name='annual_data',
            name='Consume_Natural_gas',
            field=models.FloatField(blank=True, verbose_name='天然气消耗量'),
        ),
        migrations.AlterField(
            model_name='annual_data',
            name='Consume_Other_coking_products',
            field=models.FloatField(blank=True, verbose_name='其他焦化产品消耗量'),
        ),
        migrations.AlterField(
            model_name='annual_data',
            name='Consume_Pastureland',
            field=models.FloatField(blank=True, verbose_name='畜牧地消耗量'),
        ),
        migrations.AlterField(
            model_name='annual_data',
            name='Consume_Petroleum_coke',
            field=models.FloatField(blank=True, verbose_name='石油焦消耗量'),
        ),
        migrations.AlterField(
            model_name='annual_data',
            name='Consume_Raw_coal',
            field=models.FloatField(blank=True, verbose_name='原煤消耗量'),
        ),
        migrations.AlterField(
            model_name='annual_data',
            name='Consume_Refinery_dry_gas',
            field=models.FloatField(blank=True, verbose_name='炼厂干气消耗量'),
        ),
        migrations.AlterField(
            model_name='annual_data',
            name='Consume_Steel',
            field=models.FloatField(blank=True, verbose_name='钢铁消耗量'),
        ),
        migrations.AlterField(
            model_name='annual_data',
            name='Consume_Woodland',
            field=models.FloatField(blank=True, verbose_name='林地消耗量'),
        ),
        migrations.AlterField(
            model_name='prov_annual_data',
            name='Consume_Asphalt',
            field=models.FloatField(blank=True, verbose_name='沥青消耗量'),
        ),
        migrations.AlterField(
            model_name='prov_annual_data',
            name='Consume_Briquette',
            field=models.FloatField(blank=True, verbose_name='型煤消耗量'),
        ),
        migrations.AlterField(
            model_name='prov_annual_data',
            name='Consume_Cement',
            field=models.FloatField(blank=True, verbose_name='水泥消耗量'),
        ),
        migrations.AlterField(
            model_name='prov_annual_data',
            name='Consume_Clean_coal',
            field=models.FloatField(blank=True, verbose_name='洗精煤消耗量'),
        ),
        migrations.AlterField(
            model_name='prov_annual_data',
            name='Consume_Coke',
            field=models.FloatField(blank=True, verbose_name='焦炭消耗量'),
        ),
        migrations.AlterField(
            model_name='prov_annual_data',
            name='Consume_Construction_land',
            field=models.FloatField(blank=True, verbose_name='建设用地消耗量'),
        ),
        migrations.AlterField(
            model_name='prov_annual_data',
            name='Consume_Crude',
            field=models.FloatField(blank=True, verbose_name='原油消耗量'),
        ),
        migrations.AlterField(
            model_name='prov_annual_data',
            name='Consume_Diesel',
            field=models.FloatField(blank=True, verbose_name='柴油消耗量'),
        ),
        migrations.AlterField(
            model_name='prov_annual_data',
            name='Consume_Farmland',
            field=models.FloatField(blank=True, verbose_name='农地消耗量'),
        ),
        migrations.AlterField(
            model_name='prov_annual_data',
            name='Consume_Fishing_ground',
            field=models.FloatField(blank=True, verbose_name='渔场消耗量'),
        ),
        migrations.AlterField(
            model_name='prov_annual_data',
            name='Consume_Fuel_oil',
            field=models.FloatField(blank=True, verbose_name='燃料油消耗量'),
        ),
        migrations.AlterField(
            model_name='prov_annual_data',
            name='Consume_Gasoline',
            field=models.FloatField(blank=True, verbose_name='汽油消耗量'),
        ),
        migrations.AlterField(
            model_name='prov_annual_data',
            name='Consume_Kerosene',
            field=models.FloatField(blank=True, verbose_name='煤油消耗量'),
        ),
        migrations.AlterField(
            model_name='prov_annual_data',
            name='Consume_Liquefied_petroleum_gas',
            field=models.FloatField(blank=True, verbose_name='液化石油气消耗量'),
        ),
        migrations.AlterField(
            model_name='prov_annual_data',
            name='Consume_Lubricating_oil',
            field=models.FloatField(blank=True, verbose_name='润滑油消耗量'),
        ),
        migrations.AlterField(
            model_name='prov_annual_data',
            name='Consume_Naphtha',
            field=models.FloatField(blank=True, verbose_name='石脑油消耗量'),
        ),
        migrations.AlterField(
            model_name='prov_annual_data',
            name='Consume_Natural_gas',
            field=models.FloatField(blank=True, verbose_name='天然气消耗量'),
        ),
        migrations.AlterField(
            model_name='prov_annual_data',
            name='Consume_Other_coking_products',
            field=models.FloatField(blank=True, verbose_name='其他焦化产品消耗量'),
        ),
        migrations.AlterField(
            model_name='prov_annual_data',
            name='Consume_Pastureland',
            field=models.FloatField(blank=True, verbose_name='畜牧地消耗量'),
        ),
        migrations.AlterField(
            model_name='prov_annual_data',
            name='Consume_Petroleum_coke',
            field=models.FloatField(blank=True, verbose_name='石油焦消耗量'),
        ),
        migrations.AlterField(
            model_name='prov_annual_data',
            name='Consume_Raw_coal',
            field=models.FloatField(blank=True, verbose_name='原煤消耗量'),
        ),
        migrations.AlterField(
            model_name='prov_annual_data',
            name='Consume_Refinery_dry_gas',
            field=models.FloatField(blank=True, verbose_name='炼厂干气消耗量'),
        ),
        migrations.AlterField(
            model_name='prov_annual_data',
            name='Consume_Steel',
            field=models.FloatField(blank=True, verbose_name='钢铁消耗量'),
        ),
        migrations.AlterField(
            model_name='prov_annual_data',
            name='Consume_Woodland',
            field=models.FloatField(blank=True, verbose_name='林地消耗量'),
        ),
    ]
