# Generated by Django 3.0.4 on 2020-06-10 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basework', '0003_auto_20200610_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annual_data',
            name='Consume_Briquette',
            field=models.FloatField(blank=True, default=0, verbose_name='型煤消耗量'),
        ),
    ]
