# Generated by Django 3.0.4 on 2020-06-10 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basework', '0004_auto_20200610_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annual_data',
            name='Consume_Asphalt',
            field=models.FloatField(default=0, verbose_name='沥青消耗量'),
        ),
        migrations.AlterField(
            model_name='annual_data',
            name='Consume_Briquette',
            field=models.FloatField(default=0, verbose_name='型煤消耗量'),
        ),
        migrations.AlterField(
            model_name='annual_data',
            name='Consume_Cement',
            field=models.FloatField(verbose_name='水泥消耗量'),
        ),
        migrations.AlterField(
            model_name='annual_data',
            name='Consume_Clean_coal',
            field=models.FloatField(verbose_name='洗精煤消耗量'),
        ),
        migrations.AlterField(
            model_name='annual_data',
            name='Consume_Coke',
            field=models.FloatField(verbose_name='焦炭消耗量'),
        ),
        migrations.AlterField(
            model_name='annual_data',
            name='Consume_Construction_land',
            field=models.FloatField(verbose_name='建设用地消耗量'),
        ),
        migrations.AlterField(
            model_name='annual_data',
            name='Consume_Crude',
            field=models.FloatField(verbose_name='原油消耗量'),
        ),
        migrations.AlterField(
            model_name='annual_data',
            name='Consume_Diesel',
            field=models.FloatField(verbose_name='柴油消耗量'),
        ),
        migrations.AlterField(
            model_name='annual_data',
            name='Consume_Farmland',
            field=models.FloatField(verbose_name='农地消耗量'),
        ),
        migrations.AlterField(
            model_name='annual_data',
            name='Consume_Fishing_ground',
            field=models.FloatField(verbose_name='渔场消耗量'),
        ),
        migrations.AlterField(
            model_name='annual_data',
            name='Consume_Fuel_oil',
            field=models.FloatField(verbose_name='燃料油消耗量'),
        ),
        migrations.AlterField(
            model_name='annual_data',
            name='Consume_Gasoline',
            field=models.FloatField(verbose_name='汽油消耗量'),
        ),
        migrations.AlterField(
            model_name='annual_data',
            name='Consume_Kerosene',
            field=models.FloatField(verbose_name='煤油消耗量'),
        ),
        migrations.AlterField(
            model_name='annual_data',
            name='Consume_Liquefied_petroleum_gas',
            field=models.FloatField(verbose_name='液化石油气消耗量'),
        ),
        migrations.AlterField(
            model_name='annual_data',
            name='Consume_Lubricating_oil',
            field=models.FloatField(verbose_name='润滑油消耗量'),
        ),
        migrations.AlterField(
            model_name='annual_data',
            name='Consume_Naphtha',
            field=models.FloatField(verbose_name='石脑油消耗量'),
        ),
        migrations.AlterField(
            model_name='annual_data',
            name='Consume_Natural_gas',
            field=models.FloatField(verbose_name='天然气消耗量'),
        ),
        migrations.AlterField(
            model_name='annual_data',
            name='Consume_Other_coking_products',
            field=models.FloatField(verbose_name='其他焦化产品消耗量'),
        ),
        migrations.AlterField(
            model_name='annual_data',
            name='Consume_Pastureland',
            field=models.FloatField(verbose_name='畜牧地消耗量'),
        ),
        migrations.AlterField(
            model_name='annual_data',
            name='Consume_Petroleum_coke',
            field=models.FloatField(default=0, verbose_name='石油焦消耗量'),
        ),
        migrations.AlterField(
            model_name='annual_data',
            name='Consume_Raw_coal',
            field=models.FloatField(verbose_name='原煤消耗量'),
        ),
        migrations.AlterField(
            model_name='annual_data',
            name='Consume_Refinery_dry_gas',
            field=models.FloatField(default=0, verbose_name='炼厂干气消耗量'),
        ),
        migrations.AlterField(
            model_name='annual_data',
            name='Consume_Steel',
            field=models.FloatField(verbose_name='钢铁消耗量'),
        ),
        migrations.AlterField(
            model_name='annual_data',
            name='Consume_Woodland',
            field=models.FloatField(verbose_name='林地消耗量'),
        ),
        migrations.AlterField(
            model_name='calculated_value',
            name='CO2_Emission_a',
            field=models.FloatField(null=True, verbose_name='二氧化碳排放量_年度计算值'),
        ),
        migrations.AlterField(
            model_name='calculated_value',
            name='CO2_Emission_b',
            field=models.FloatField(null=True, verbose_name='二氧化碳排放量_年度计算值'),
        ),
        migrations.AlterField(
            model_name='calculated_value',
            name='Cal_Asphalt',
            field=models.FloatField(null=True, verbose_name='沥青_年度计算值'),
        ),
        migrations.AlterField(
            model_name='calculated_value',
            name='Cal_Briquette',
            field=models.FloatField(null=True, verbose_name='型煤_年度计算值'),
        ),
        migrations.AlterField(
            model_name='calculated_value',
            name='Cal_Cement',
            field=models.FloatField(null=True, verbose_name='水泥_年度计算值'),
        ),
        migrations.AlterField(
            model_name='calculated_value',
            name='Cal_Clean_coal',
            field=models.FloatField(null=True, verbose_name='洗精煤_年度计算值'),
        ),
        migrations.AlterField(
            model_name='calculated_value',
            name='Cal_Coke',
            field=models.FloatField(null=True, verbose_name='焦炭_年度计算值'),
        ),
        migrations.AlterField(
            model_name='calculated_value',
            name='Cal_Crude',
            field=models.FloatField(null=True, verbose_name='原油_年度计算值'),
        ),
        migrations.AlterField(
            model_name='calculated_value',
            name='Cal_Diesel',
            field=models.FloatField(null=True, verbose_name='柴油_年度计算值'),
        ),
        migrations.AlterField(
            model_name='calculated_value',
            name='Cal_EF',
            field=models.FloatField(null=True, verbose_name='生态足迹_年度计算值'),
        ),
        migrations.AlterField(
            model_name='calculated_value',
            name='Cal_Fuel_oil',
            field=models.FloatField(null=True, verbose_name='燃料油_年度计算值'),
        ),
        migrations.AlterField(
            model_name='calculated_value',
            name='Cal_Gasoline',
            field=models.FloatField(null=True, verbose_name='汽油_年度计算值'),
        ),
        migrations.AlterField(
            model_name='calculated_value',
            name='Cal_Kerosene',
            field=models.FloatField(null=True, verbose_name='煤油_年度计算值'),
        ),
        migrations.AlterField(
            model_name='calculated_value',
            name='Cal_Liquefied_petroleum_gas',
            field=models.FloatField(null=True, verbose_name='液化石油气_年度计算值'),
        ),
        migrations.AlterField(
            model_name='calculated_value',
            name='Cal_Lubricating_oil',
            field=models.FloatField(null=True, verbose_name='润滑油_年度计算值'),
        ),
        migrations.AlterField(
            model_name='calculated_value',
            name='Cal_Naphtha',
            field=models.FloatField(null=True, verbose_name='石脑油_年度计算值'),
        ),
        migrations.AlterField(
            model_name='calculated_value',
            name='Cal_Natural_gas',
            field=models.FloatField(null=True, verbose_name='天然气_年度计算值'),
        ),
        migrations.AlterField(
            model_name='calculated_value',
            name='Cal_Other_coking_products',
            field=models.FloatField(null=True, verbose_name='其他焦化产品_年度计算值'),
        ),
        migrations.AlterField(
            model_name='calculated_value',
            name='Cal_Petroleum_coke',
            field=models.FloatField(null=True, verbose_name='石油焦_年度计算值'),
        ),
        migrations.AlterField(
            model_name='calculated_value',
            name='Cal_Raw_coal',
            field=models.FloatField(null=True, verbose_name='原煤_年度计算值'),
        ),
        migrations.AlterField(
            model_name='calculated_value',
            name='Cal_Refinery_dry_gas',
            field=models.FloatField(null=True, verbose_name='炼厂干气_年度计算值'),
        ),
        migrations.AlterField(
            model_name='calculated_value',
            name='Cal_Steel',
            field=models.FloatField(null=True, verbose_name='钢铁_年度计算值'),
        ),
        migrations.AlterField(
            model_name='calculated_value',
            name='GHG_Emission_a',
            field=models.FloatField(null=True, verbose_name='温室气体排放量_年度计算值'),
        ),
        migrations.AlterField(
            model_name='calculated_value',
            name='GHG_Emission_b',
            field=models.FloatField(null=True, verbose_name='温室气体排放量_年度计算值'),
        ),
        migrations.AlterField(
            model_name='calculated_value',
            name='Total_CO2_Emission',
            field=models.FloatField(null=True, verbose_name='二氧化碳排放总量_年度计算值'),
        ),
        migrations.AlterField(
            model_name='calculated_value',
            name='co2_per_gdp',
            field=models.FloatField(null=True, verbose_name='单位GDP二氧化碳排放量'),
        ),
        migrations.AlterField(
            model_name='calculated_value',
            name='edu_years',
            field=models.FloatField(null=True, verbose_name='平均受教育年限'),
        ),
        migrations.AlterField(
            model_name='calculated_value',
            name='ef_per',
            field=models.FloatField(null=True, verbose_name='人均生态足迹'),
        ),
        migrations.AlterField(
            model_name='calculated_value',
            name='medical_cov',
            field=models.FloatField(null=True, verbose_name='医疗保险覆盖率'),
        ),
        migrations.AlterField(
            model_name='calculated_value',
            name='pension_cov',
            field=models.FloatField(null=True, verbose_name='养老保险覆盖率'),
        ),
        migrations.AlterField(
            model_name='calculated_value',
            name='per_unit_gdp',
            field=models.FloatField(null=True, verbose_name='单位GDP能耗'),
        ),
        migrations.AlterField(
            model_name='calculated_value',
            name='planting_area',
            field=models.FloatField(null=True, verbose_name='播种面积占比'),
        ),
        migrations.AlterField(
            model_name='calculated_value',
            name='renewable_energy_per',
            field=models.FloatField(null=True, verbose_name='可再生能源供给占比(省)'),
        ),
        migrations.AlterField(
            model_name='calculated_value',
            name='unemployment_cov',
            field=models.FloatField(null=True, verbose_name='失业保险覆盖率'),
        ),
        migrations.AlterField(
            model_name='calculated_value',
            name='water_per',
            field=models.FloatField(null=True, verbose_name='人均用水量'),
        ),
        migrations.AlterField(
            model_name='calculated_value',
            name='water_per_gdp',
            field=models.FloatField(null=True, verbose_name='单位GDP用水量'),
        ),
        migrations.AlterField(
            model_name='prov_annual_data',
            name='Consume_Asphalt',
            field=models.FloatField(default=0, verbose_name='沥青消耗量'),
        ),
        migrations.AlterField(
            model_name='prov_annual_data',
            name='Consume_Briquette',
            field=models.FloatField(default=0, verbose_name='型煤消耗量'),
        ),
        migrations.AlterField(
            model_name='prov_annual_data',
            name='Consume_Cement',
            field=models.FloatField(verbose_name='水泥消耗量'),
        ),
        migrations.AlterField(
            model_name='prov_annual_data',
            name='Consume_Clean_coal',
            field=models.FloatField(verbose_name='洗精煤消耗量'),
        ),
        migrations.AlterField(
            model_name='prov_annual_data',
            name='Consume_Coke',
            field=models.FloatField(verbose_name='焦炭消耗量'),
        ),
        migrations.AlterField(
            model_name='prov_annual_data',
            name='Consume_Construction_land',
            field=models.FloatField(verbose_name='建设用地消耗量'),
        ),
        migrations.AlterField(
            model_name='prov_annual_data',
            name='Consume_Crude',
            field=models.FloatField(verbose_name='原油消耗量'),
        ),
        migrations.AlterField(
            model_name='prov_annual_data',
            name='Consume_Diesel',
            field=models.FloatField(verbose_name='柴油消耗量'),
        ),
        migrations.AlterField(
            model_name='prov_annual_data',
            name='Consume_Farmland',
            field=models.FloatField(verbose_name='农地消耗量'),
        ),
        migrations.AlterField(
            model_name='prov_annual_data',
            name='Consume_Fishing_ground',
            field=models.FloatField(verbose_name='渔场消耗量'),
        ),
        migrations.AlterField(
            model_name='prov_annual_data',
            name='Consume_Fuel_oil',
            field=models.FloatField(verbose_name='燃料油消耗量'),
        ),
        migrations.AlterField(
            model_name='prov_annual_data',
            name='Consume_Gasoline',
            field=models.FloatField(verbose_name='汽油消耗量'),
        ),
        migrations.AlterField(
            model_name='prov_annual_data',
            name='Consume_Kerosene',
            field=models.FloatField(verbose_name='煤油消耗量'),
        ),
        migrations.AlterField(
            model_name='prov_annual_data',
            name='Consume_Liquefied_petroleum_gas',
            field=models.FloatField(verbose_name='液化石油气消耗量'),
        ),
        migrations.AlterField(
            model_name='prov_annual_data',
            name='Consume_Lubricating_oil',
            field=models.FloatField(verbose_name='润滑油消耗量'),
        ),
        migrations.AlterField(
            model_name='prov_annual_data',
            name='Consume_Naphtha',
            field=models.FloatField(verbose_name='石脑油消耗量'),
        ),
        migrations.AlterField(
            model_name='prov_annual_data',
            name='Consume_Natural_gas',
            field=models.FloatField(verbose_name='天然气消耗量'),
        ),
        migrations.AlterField(
            model_name='prov_annual_data',
            name='Consume_Other_coking_products',
            field=models.FloatField(verbose_name='其他焦化产品消耗量'),
        ),
        migrations.AlterField(
            model_name='prov_annual_data',
            name='Consume_Pastureland',
            field=models.FloatField(verbose_name='畜牧地消耗量'),
        ),
        migrations.AlterField(
            model_name='prov_annual_data',
            name='Consume_Petroleum_coke',
            field=models.FloatField(default=0, verbose_name='石油焦消耗量'),
        ),
        migrations.AlterField(
            model_name='prov_annual_data',
            name='Consume_Raw_coal',
            field=models.FloatField(verbose_name='原煤消耗量'),
        ),
        migrations.AlterField(
            model_name='prov_annual_data',
            name='Consume_Refinery_dry_gas',
            field=models.FloatField(default=0, verbose_name='炼厂干气消耗量'),
        ),
        migrations.AlterField(
            model_name='prov_annual_data',
            name='Consume_Steel',
            field=models.FloatField(verbose_name='钢铁消耗量'),
        ),
        migrations.AlterField(
            model_name='prov_annual_data',
            name='Consume_Woodland',
            field=models.FloatField(verbose_name='林地消耗量'),
        ),
        migrations.AlterField(
            model_name='prov_calculated_value',
            name='CO2_Emission_a',
            field=models.FloatField(null=True, verbose_name='二氧化碳排放量_年度计算值'),
        ),
        migrations.AlterField(
            model_name='prov_calculated_value',
            name='CO2_Emission_b',
            field=models.FloatField(null=True, verbose_name='二氧化碳排放量_年度计算值'),
        ),
        migrations.AlterField(
            model_name='prov_calculated_value',
            name='Cal_Asphalt',
            field=models.FloatField(null=True, verbose_name='沥青_年度计算值'),
        ),
        migrations.AlterField(
            model_name='prov_calculated_value',
            name='Cal_Briquette',
            field=models.FloatField(null=True, verbose_name='型煤_年度计算值'),
        ),
        migrations.AlterField(
            model_name='prov_calculated_value',
            name='Cal_Cement',
            field=models.FloatField(null=True, verbose_name='水泥_年度计算值'),
        ),
        migrations.AlterField(
            model_name='prov_calculated_value',
            name='Cal_Clean_coal',
            field=models.FloatField(null=True, verbose_name='洗精煤_年度计算值'),
        ),
        migrations.AlterField(
            model_name='prov_calculated_value',
            name='Cal_Coke',
            field=models.FloatField(null=True, verbose_name='焦炭_年度计算值'),
        ),
        migrations.AlterField(
            model_name='prov_calculated_value',
            name='Cal_Crude',
            field=models.FloatField(null=True, verbose_name='原油_年度计算值'),
        ),
        migrations.AlterField(
            model_name='prov_calculated_value',
            name='Cal_Diesel',
            field=models.FloatField(null=True, verbose_name='柴油_年度计算值'),
        ),
        migrations.AlterField(
            model_name='prov_calculated_value',
            name='Cal_EF',
            field=models.FloatField(null=True, verbose_name='生态足迹_年度计算值'),
        ),
        migrations.AlterField(
            model_name='prov_calculated_value',
            name='Cal_Fuel_oil',
            field=models.FloatField(null=True, verbose_name='燃料油_年度计算值'),
        ),
        migrations.AlterField(
            model_name='prov_calculated_value',
            name='Cal_Gasoline',
            field=models.FloatField(null=True, verbose_name='汽油_年度计算值'),
        ),
        migrations.AlterField(
            model_name='prov_calculated_value',
            name='Cal_Kerosene',
            field=models.FloatField(null=True, verbose_name='煤油_年度计算值'),
        ),
        migrations.AlterField(
            model_name='prov_calculated_value',
            name='Cal_Liquefied_petroleum_gas',
            field=models.FloatField(null=True, verbose_name='液化石油气_年度计算值'),
        ),
        migrations.AlterField(
            model_name='prov_calculated_value',
            name='Cal_Lubricating_oil',
            field=models.FloatField(null=True, verbose_name='润滑油_年度计算值'),
        ),
        migrations.AlterField(
            model_name='prov_calculated_value',
            name='Cal_Naphtha',
            field=models.FloatField(null=True, verbose_name='石脑油_年度计算值'),
        ),
        migrations.AlterField(
            model_name='prov_calculated_value',
            name='Cal_Natural_gas',
            field=models.FloatField(null=True, verbose_name='天然气_年度计算值'),
        ),
        migrations.AlterField(
            model_name='prov_calculated_value',
            name='Cal_Other_coking_products',
            field=models.FloatField(null=True, verbose_name='其他焦化产品_年度计算值'),
        ),
        migrations.AlterField(
            model_name='prov_calculated_value',
            name='Cal_Petroleum_coke',
            field=models.FloatField(null=True, verbose_name='石油焦_年度计算值'),
        ),
        migrations.AlterField(
            model_name='prov_calculated_value',
            name='Cal_Raw_coal',
            field=models.FloatField(null=True, verbose_name='原煤_年度计算值'),
        ),
        migrations.AlterField(
            model_name='prov_calculated_value',
            name='Cal_Refinery_dry_gas',
            field=models.FloatField(null=True, verbose_name='炼厂干气_年度计算值'),
        ),
        migrations.AlterField(
            model_name='prov_calculated_value',
            name='Cal_Steel',
            field=models.FloatField(null=True, verbose_name='钢铁_年度计算值'),
        ),
        migrations.AlterField(
            model_name='prov_calculated_value',
            name='GHG_Emission_a',
            field=models.FloatField(null=True, verbose_name='温室气体排放量_年度计算值'),
        ),
        migrations.AlterField(
            model_name='prov_calculated_value',
            name='GHG_Emission_b',
            field=models.FloatField(null=True, verbose_name='温室气体排放量_年度计算值'),
        ),
        migrations.AlterField(
            model_name='prov_calculated_value',
            name='Total_CO2_Emission',
            field=models.FloatField(null=True, verbose_name='二氧化碳排放总量_年度计算值'),
        ),
        migrations.AlterField(
            model_name='prov_calculated_value',
            name='co2_per_gdp',
            field=models.FloatField(null=True, verbose_name='单位GDP二氧化碳排放量'),
        ),
        migrations.AlterField(
            model_name='prov_calculated_value',
            name='edu_years',
            field=models.FloatField(null=True, verbose_name='平均受教育年限'),
        ),
        migrations.AlterField(
            model_name='prov_calculated_value',
            name='ef_per',
            field=models.FloatField(null=True, verbose_name='人均生态足迹'),
        ),
        migrations.AlterField(
            model_name='prov_calculated_value',
            name='medical_cov',
            field=models.FloatField(null=True, verbose_name='医疗保险覆盖率'),
        ),
        migrations.AlterField(
            model_name='prov_calculated_value',
            name='pension_cov',
            field=models.FloatField(null=True, verbose_name='养老保险覆盖率'),
        ),
        migrations.AlterField(
            model_name='prov_calculated_value',
            name='per_unit_gdp',
            field=models.FloatField(null=True, verbose_name='单位GDP能耗'),
        ),
        migrations.AlterField(
            model_name='prov_calculated_value',
            name='planting_area',
            field=models.FloatField(null=True, verbose_name='播种面积占比'),
        ),
        migrations.AlterField(
            model_name='prov_calculated_value',
            name='renewable_energy_per',
            field=models.FloatField(null=True, verbose_name='可再生能源供给占比(省)'),
        ),
        migrations.AlterField(
            model_name='prov_calculated_value',
            name='unemployment_cov',
            field=models.FloatField(null=True, verbose_name='失业保险覆盖率'),
        ),
        migrations.AlterField(
            model_name='prov_calculated_value',
            name='water_per',
            field=models.FloatField(null=True, verbose_name='人均用水量'),
        ),
        migrations.AlterField(
            model_name='prov_calculated_value',
            name='water_per_gdp',
            field=models.FloatField(null=True, verbose_name='单位GDP用水量'),
        ),
    ]
