# Generated by Django 3.0.4 on 2020-06-12 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basework', '0006_importfile_excel_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='importfile_excel',
            name='arealevel',
            field=models.CharField(choices=[('area', '市级'), ('province', '省级')], default=('area', '市级'), max_length=50, verbose_name='数据级别'),
            preserve_default=False,
        ),
    ]
