# Generated by Django 3.0.4 on 2020-06-12 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0013_auto_20200317_0930'),
        ('basework', '0007_importfile_excel_arealevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='importfile_excel',
            name='province',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='work.Province', verbose_name='省份'),
            preserve_default=False,
        ),
    ]
