# Generated by Django 3.0.4 on 2020-06-13 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basework', '0008_importfile_excel_province'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importfile_excel',
            name='name',
        ),
    ]
