# Generated by Django 3.0.4 on 2020-06-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basework', '0009_remove_importfile_excel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importfile_excel',
            name='excelfile',
            field=models.FileField(upload_to='data/%Y-%m-%d', verbose_name='上传'),
        ),
    ]
