# Generated by Django 3.0.4 on 2020-06-13 08:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('basework', '0010_auto_20200613_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='importfile_excel',
            name='add_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='上传日期'),
        ),
    ]
