# Generated by Django 3.0.4 on 2020-06-13 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basework', '0011_importfile_excel_add_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importfile_excel',
            name='add_date',
            field=models.DateTimeField(auto_now=True, verbose_name='上传日期'),
        ),
    ]
