# Generated by Django 3.0.4 on 2020-06-14 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basework', '0012_auto_20200613_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annual_data',
            name='Hydropower_generation',
        ),
        migrations.RemoveField(
            model_name='annual_data',
            name='Nuclear_power_generation',
        ),
        migrations.RemoveField(
            model_name='annual_data',
            name='Photovoltaic_power_generation',
        ),
        migrations.RemoveField(
            model_name='annual_data',
            name='Total_power_generation',
        ),
        migrations.RemoveField(
            model_name='annual_data',
            name='Wind_power_generation',
        ),
        migrations.RemoveField(
            model_name='calculated_value',
            name='renewable_energy_per',
        ),
    ]
