# Generated by Django 3.0.4 on 2020-03-07 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='区域名称')),
            ],
            options={
                'verbose_name': '地区',
                'verbose_name_plural': '地区',
                'ordering': ('province', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='标题')),
                ('author', models.CharField(blank=True, max_length=64, null=True, verbose_name='作者')),
                ('info', models.CharField(blank=True, max_length=255, null=True, verbose_name='摘要')),
                ('body', models.TextField(verbose_name='正文')),
                ('pub_date', models.DateTimeField(verbose_name='文章日期')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='发表日志')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='最后编辑')),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='省份名称')),
            ],
            options={
                'verbose_name': '省份',
                'verbose_name_plural': '省份',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='DataRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='年度')),
                ('r_d', models.FloatField(verbose_name='规模以上工业企业R&D经费支出')),
                ('per_unit_gdp', models.FloatField(verbose_name='单位GDP能耗')),
                ('rural_urban', models.FloatField(verbose_name='乡-城人均年收入比')),
                ('urban_per', models.FloatField(verbose_name='城镇居民人均可支配收入')),
                ('rural_per', models.FloatField(verbose_name='农村居民人均可支配收入')),
                ('garbage', models.FloatField(verbose_name='生活垃圾无害化处理率')),
                ('bus_per', models.FloatField(verbose_name='平均万人拥有公共汽车')),
                ('urban_sewage', models.FloatField(verbose_name='城镇生活污水集中处理率')),
                ('edu_years', models.FloatField(verbose_name='平均受教育年限')),
                ('mortality', models.FloatField(verbose_name='死亡率')),
                ('pension_cov', models.FloatField(verbose_name='养老保险覆盖率')),
                ('medical_cov', models.FloatField(verbose_name='医疗保险覆盖率')),
                ('unemployment_cov', models.FloatField(verbose_name='失业保险覆盖率')),
                ('pm25', models.FloatField(verbose_name='PM2.5年平均浓度')),
                ('so2_emissions', models.FloatField(verbose_name='二氧化硫排放量')),
                ('co2_per_gdp', models.FloatField(verbose_name='单位GDP二氧化碳排放量')),
                ('cod_emissions', models.FloatField(verbose_name='化学需氧量排放量')),
                ('nh_emissions', models.FloatField(verbose_name='氨氮排放量')),
                ('water_per', models.FloatField(verbose_name='人均耗水量')),
                ('water_per_gdp', models.FloatField(verbose_name='单位GDP用水量')),
                ('planting_area', models.FloatField(verbose_name='播种面积占比')),
                ('ef_per', models.FloatField(verbose_name='人均生态足迹')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_record_ls', to='work.Area', verbose_name='地区')),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_ls', to='work.Province', verbose_name='所属省份'),
        ),
    ]
