# Generated by Django 3.0.4 on 2020-03-13 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_auto_20200313_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='附件名称')),
                ('attach', models.FileField(upload_to='%Y-%m-%d', verbose_name='附件')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attach_ls', to='work.Article')),
            ],
        ),
    ]
