# Generated by Django 3.0.4 on 2020-03-13 06:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_attach'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attach',
            options={'ordering': ('-created',), 'verbose_name': '附件', 'verbose_name_plural': '附件'},
        ),
        migrations.AlterModelOptions(
            name='citydatarecord',
            options={'ordering': ('-year', 'area'), 'verbose_name': '地区数据', 'verbose_name_plural': '地区数据'},
        ),
        migrations.AlterModelOptions(
            name='provincedatarecord',
            options={'ordering': ('-year', 'province'), 'verbose_name': '省份数据', 'verbose_name_plural': '省份数据'},
        ),
        migrations.AddField(
            model_name='attach',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='上传时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attach',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
    ]
