# Generated by Django 3.0.4 on 2020-03-13 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_auto_20200313_1431'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attach',
            options={'ordering': ('-created', 'name', 'attach'), 'verbose_name': '附件', 'verbose_name_plural': '附件'},
        ),
    ]
