# Generated by Django 3.0.4 on 2020-03-13 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_auto_20200313_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='provincedatarecord',
            name='attach',
            field=models.FileField(default='data/数据模板.xlsx', upload_to='data/%Y-%m-%d', verbose_name='年度省内各地区数据'),
        ),
        migrations.AlterField(
            model_name='attach',
            name='attach',
            field=models.FileField(upload_to='attach/%Y-%m-%d', verbose_name='附件'),
        ),
    ]
