# Generated by Django 3.0.4 on 2020-03-14 13:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import work.models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0006_auto_20200313_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='citydatarecord',
            name='province_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cities_records', to='work.ProvinceDataRecord'),
        ),
        migrations.AlterField(
            model_name='provincedatarecord',
            name='attach',
            field=models.FileField(default='data/数据模板.xlsx', upload_to='data/%Y-%m-%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('xlsx',), message='仅支持上传扩展名为 xlsx 的Excel文件'), work.models.import_excel_validator], verbose_name='年度省内各地区数据'),
        ),
        migrations.AlterUniqueTogether(
            name='citydatarecord',
            unique_together={('area', 'year')},
        ),
    ]
