# Generated by Django 3.0.4 on 2020-03-14 14:40

from django.db import migrations, models
import work.models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0007_auto_20200314_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citydatarecord',
            name='bus_per',
            field=models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='平均万人拥有公共汽车'),
        ),
        migrations.AlterField(
            model_name='citydatarecord',
            name='co2_per_gdp',
            field=models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='单位GDP二氧化碳排放量'),
        ),
        migrations.AlterField(
            model_name='citydatarecord',
            name='cod_emissions',
            field=models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='化学需氧量排放量'),
        ),
        migrations.AlterField(
            model_name='citydatarecord',
            name='edu_years',
            field=models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='平均受教育年限'),
        ),
        migrations.AlterField(
            model_name='citydatarecord',
            name='ef_per',
            field=models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='人均生态足迹'),
        ),
        migrations.AlterField(
            model_name='citydatarecord',
            name='garbage',
            field=models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='生活垃圾无害化处理率'),
        ),
        migrations.AlterField(
            model_name='citydatarecord',
            name='medical_cov',
            field=models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='医疗保险覆盖率'),
        ),
        migrations.AlterField(
            model_name='citydatarecord',
            name='mortality',
            field=models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='死亡率'),
        ),
        migrations.AlterField(
            model_name='citydatarecord',
            name='nh_emissions',
            field=models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='氨氮排放量'),
        ),
        migrations.AlterField(
            model_name='citydatarecord',
            name='pension_cov',
            field=models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='养老保险覆盖率'),
        ),
        migrations.AlterField(
            model_name='citydatarecord',
            name='per_unit_gdp',
            field=models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='单位GDP能耗'),
        ),
        migrations.AlterField(
            model_name='citydatarecord',
            name='planting_area',
            field=models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='播种面积占比'),
        ),
        migrations.AlterField(
            model_name='citydatarecord',
            name='pm25',
            field=models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='PM2.5年平均浓度'),
        ),
        migrations.AlterField(
            model_name='citydatarecord',
            name='r_d',
            field=models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='规模以上工业企业R&D经费支出'),
        ),
        migrations.AlterField(
            model_name='citydatarecord',
            name='rural_per',
            field=models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='农村居民人均可支配收入'),
        ),
        migrations.AlterField(
            model_name='citydatarecord',
            name='rural_urban',
            field=models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='乡-城人均年收入比'),
        ),
        migrations.AlterField(
            model_name='citydatarecord',
            name='so2_emissions',
            field=models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='二氧化硫排放量'),
        ),
        migrations.AlterField(
            model_name='citydatarecord',
            name='unemployment_cov',
            field=models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='失业保险覆盖率'),
        ),
        migrations.AlterField(
            model_name='citydatarecord',
            name='urban_per',
            field=models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='城镇居民人均可支配收入'),
        ),
        migrations.AlterField(
            model_name='citydatarecord',
            name='urban_sewage',
            field=models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='城镇生活污水集中处理率'),
        ),
        migrations.AlterField(
            model_name='citydatarecord',
            name='water_per',
            field=models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='人均耗水量'),
        ),
        migrations.AlterField(
            model_name='citydatarecord',
            name='water_per_gdp',
            field=models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='单位GDP用水量'),
        ),
        migrations.AlterField(
            model_name='provincedatarecord',
            name='bus_per',
            field=models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='平均万人拥有公共汽车'),
        ),
        migrations.AlterField(
            model_name='provincedatarecord',
            name='bus_per_target',
            field=models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='平均万人拥有公共汽车的目标值'),
        ),
        migrations.AlterField(
            model_name='provincedatarecord',
            name='co2_per_gdp',
            field=models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='单位GDP二氧化碳排放量'),
        ),
        migrations.AlterField(
            model_name='provincedatarecord',
            name='co2_per_gdp_target',
            field=models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='单位GDP二氧化碳排放量的目标值'),
        ),
        migrations.AlterField(
            model_name='provincedatarecord',
            name='cod_emissions',
            field=models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='化学需氧量排放量'),
        ),
        migrations.AlterField(
            model_name='provincedatarecord',
            name='cod_emissions_target',
            field=models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='化学需氧量排放量的目标值'),
        ),
        migrations.AlterField(
            model_name='provincedatarecord',
            name='edu_years',
            field=models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='平均受教育年限'),
        ),
        migrations.AlterField(
            model_name='provincedatarecord',
            name='edu_years_target',
            field=models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='平均受教育年限的目标值'),
        ),
        migrations.AlterField(
            model_name='provincedatarecord',
            name='ef_per',
            field=models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='人均生态足迹'),
        ),
        migrations.AlterField(
            model_name='provincedatarecord',
            name='ef_per_target',
            field=models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='人均生态足迹的目标值'),
        ),
        migrations.AlterField(
            model_name='provincedatarecord',
            name='garbage',
            field=models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='生活垃圾无害化处理率'),
        ),
        migrations.AlterField(
            model_name='provincedatarecord',
            name='garbage_target',
            field=models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='生活垃圾无害化处理率的目标值'),
        ),
        migrations.AlterField(
            model_name='provincedatarecord',
            name='medical_cov',
            field=models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='医疗保险覆盖率'),
        ),
        migrations.AlterField(
            model_name='provincedatarecord',
            name='medical_cov_target',
            field=models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='医疗保险覆盖率的目标值'),
        ),
        migrations.AlterField(
            model_name='provincedatarecord',
            name='mortality',
            field=models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='死亡率'),
        ),
        migrations.AlterField(
            model_name='provincedatarecord',
            name='mortality_target',
            field=models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='死亡率的目标值'),
        ),
        migrations.AlterField(
            model_name='provincedatarecord',
            name='nh_emissions',
            field=models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='氨氮排放量'),
        ),
        migrations.AlterField(
            model_name='provincedatarecord',
            name='nh_emissions_target',
            field=models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='氨氮排放量的目标值'),
        ),
        migrations.AlterField(
            model_name='provincedatarecord',
            name='pension_cov',
            field=models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='养老保险覆盖率'),
        ),
        migrations.AlterField(
            model_name='provincedatarecord',
            name='pension_cov_target',
            field=models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='养老保险覆盖率的目标值'),
        ),
        migrations.AlterField(
            model_name='provincedatarecord',
            name='per_unit_gdp',
            field=models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='单位GDP能耗'),
        ),
        migrations.AlterField(
            model_name='provincedatarecord',
            name='per_unit_gdp_target',
            field=models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='单位GDP能耗的目标值'),
        ),
        migrations.AlterField(
            model_name='provincedatarecord',
            name='planting_area',
            field=models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='播种面积占比'),
        ),
        migrations.AlterField(
            model_name='provincedatarecord',
            name='planting_area_target',
            field=models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='播种面积占比的目标值'),
        ),
        migrations.AlterField(
            model_name='provincedatarecord',
            name='pm25',
            field=models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='PM2.5年平均浓度'),
        ),
        migrations.AlterField(
            model_name='provincedatarecord',
            name='pm25_target',
            field=models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='PM2.5年平均浓度的目标值'),
        ),
        migrations.AlterField(
            model_name='provincedatarecord',
            name='r_d',
            field=models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='规模以上工业企业R&D经费支出'),
        ),
        migrations.AlterField(
            model_name='provincedatarecord',
            name='r_d_target',
            field=models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='规模以上工业企业R&D经费支出的目标值'),
        ),
        migrations.AlterField(
            model_name='provincedatarecord',
            name='rural_per',
            field=models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='农村居民人均可支配收入'),
        ),
        migrations.AlterField(
            model_name='provincedatarecord',
            name='rural_per_target',
            field=models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='农村居民人均可支配收入的目标值'),
        ),
        migrations.AlterField(
            model_name='provincedatarecord',
            name='rural_urban',
            field=models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='乡-城人均年收入比'),
        ),
        migrations.AlterField(
            model_name='provincedatarecord',
            name='rural_urban_target',
            field=models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='乡-城人均年收入比的目标值'),
        ),
        migrations.AlterField(
            model_name='provincedatarecord',
            name='so2_emissions',
            field=models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='二氧化硫排放量'),
        ),
        migrations.AlterField(
            model_name='provincedatarecord',
            name='so2_emissions_target',
            field=models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='二氧化硫排放量的目标值'),
        ),
        migrations.AlterField(
            model_name='provincedatarecord',
            name='unemployment_cov',
            field=models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='失业保险覆盖率'),
        ),
        migrations.AlterField(
            model_name='provincedatarecord',
            name='unemployment_cov_target',
            field=models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='失业保险覆盖率的目标值'),
        ),
        migrations.AlterField(
            model_name='provincedatarecord',
            name='urban_per',
            field=models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='城镇居民人均可支配收入'),
        ),
        migrations.AlterField(
            model_name='provincedatarecord',
            name='urban_per_target',
            field=models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='城镇居民人均可支配收入的目标值'),
        ),
        migrations.AlterField(
            model_name='provincedatarecord',
            name='urban_sewage',
            field=models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='城镇生活污水集中处理率'),
        ),
        migrations.AlterField(
            model_name='provincedatarecord',
            name='urban_sewage_target',
            field=models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='城镇生活污水集中处理率的目标值'),
        ),
        migrations.AlterField(
            model_name='provincedatarecord',
            name='water_per',
            field=models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='人均耗水量'),
        ),
        migrations.AlterField(
            model_name='provincedatarecord',
            name='water_per_gdp',
            field=models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='单位GDP用水量'),
        ),
        migrations.AlterField(
            model_name='provincedatarecord',
            name='water_per_gdp_target',
            field=models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='单位GDP用水量的目标值'),
        ),
        migrations.AlterField(
            model_name='provincedatarecord',
            name='water_per_target',
            field=models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='人均耗水量的目标值'),
        ),
    ]
