# Generated by Django 3.0.4 on 2020-03-15 03:50

from django.db import migrations, models
import work.models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0008_auto_20200314_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='provincedatarecord',
            name='renewable_energy',
            field=models.FloatField(blank=True, null=True, validators=[work.models.can_not_equal_zero], verbose_name='可再生能源供给'),
        ),
        migrations.AddField(
            model_name='provincedatarecord',
            name='renewable_energy_per',
            field=models.FloatField(default=1, validators=[work.models.can_not_equal_zero], verbose_name='可再生能源供给占比'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='provincedatarecord',
            name='r_d',
            field=models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='企业 R&D 内部经费支出'),
        ),
        migrations.AlterField(
            model_name='provincedatarecord',
            name='r_d_target',
            field=models.FloatField(validators=[work.models.can_not_equal_zero], verbose_name='企业 R&D 内部经费支出的目标值'),
        ),
    ]
