# Generated by Django 3.0.4 on 2020-03-15 03:55

from django.db import migrations, models
import work.models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0009_auto_20200315_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='provincedatarecord',
            name='renewable_energy_per_target',
            field=models.FloatField(default=1, validators=[work.models.can_not_equal_zero], verbose_name='可再生能源供给占比的目标值'),
            preserve_default=False,
        ),
    ]
