# Generated by Django 3.0.4 on 2020-03-15 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0010_provincedatarecord_renewable_energy_per_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='provincedatarecord',
            name='status',
            field=models.SmallIntegerField(default=1, verbose_name='状态'),
        ),
    ]
